### ISSUE TITLE
[Loon] iRingo插件和Apple分流规则取舍

### ISSUE THREAD

**Issue by wyq977** [Elysian-Realme/FuGfConfig#1]
根据 https://github.com/chiupam/tutorial/blob/master/Loon/Plus/Plugin_Summary.md

Loon里面Plugin优先级最高 相当于另外一个conf

那用了 iRingo之后还需要继续 用分流规则吗 AppleCDN之类的

我问是因为iRingo里面也有RuleSet 和URL Rewrite 用[Apple_News.plugin](https://github.com/VirgilClyne/iRingo/blob/main/plugin/Apple_News.plugin)就有apple news的分流

但是iRingo好像没有iCloud iTunes Store app store等分流规则 所以我猜想还得同时加上这些 免得美区账号走直连被风控封死

谢谢

**Comment by dunlanl** [comment]
小孩子才做选择,我全都要😉

我的本意是让大家先采用 iRingo 的插件,如果插件禁用了,或者用不到 iRingo 插件,再采用本项目的 Apple 分流规则

**Comment by dunlanl** [comment]
> 根据 https://github.com/chiupam/tutorial/blob/master/Loon/Plus/Plugin_Summary.md
> 
> 
> 
> Loon里面Plugin优先级最高 相当于另外一个conf
> 
> 
> 
> 那用了 iRingo之后还需要继续 用分流规则吗 AppleCDN之类的
> 
> 
> 
> 我问是因为iRingo里面也有RuleSet 和URL Rewrite 用[Apple_News.plugin](https://github.com/VirgilClyne/iRingo/blob/main/plugin/Apple_News.plugin)就有apple news的分流
> 
> 
> 
> 但是iRingo好像没有iCloud iTunes Store app store等分流规则 所以我猜想还得同时加上这些 免得美区账号走直连被风控封死
> 
> 
> 
> 谢谢

是的,需要同时加上,我美区账号,一直直连,感觉问题不大
