### ISSUE TITLE
iOS 系统更新屏蔽里的 QX 规则是否有误

### ISSUE THREAD

**Issue by OffshoreCode** [Elysian-Realme/FuGfConfig#10]
您好，
请问 iOS 系统更新里面的规则中有一个 AppleAll 的选项，这个选项是否非必须的或者改成 direct? 因为直接复制到 QX 中会报错
谢谢！

# qx
static= AppleUpdate, reject, **AppleAll**, img-url = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple_Update.png

**Comment by TruElysian** [comment]
您好

可以改成直连
