### ISSUE TITLE
Surge 导入 AppleRules 时解析失败

### ISSUE THREAD

**Issue by CN-GuoZiyang** [Elysian-Realme/FuGfConfig#11]
规则集 Rule：
RULE-SET,https://raw.githubusercontent.com/Elysian-Realme/FuGfConfig/main/ConfigFile/Surge/Apple/AppleRules.conf,DIRECT

更新时会报 Failed to parse remote resource data 错误

**Comment by TruElysian** [comment]
您好，针对 Surge，参考 [https://manual.nssurge.com/rule/ruleset.html](https://manual.nssurge.com/rule/ruleset.html)，请使用 `RULE-SET,SYSTEM,DIRECT`，忽略 `Surge/Apple/AppleRules.conf` 文件。
我接手时对 Surge 了解不深，照搬了上一任维护者的 Loon 规则，后续会添加对 Surge 的规则说明和优化
