### ISSUE TITLE
使用Qx，网络活动里看不见Facetime的请求

### ISSUE THREAD

**Issue by sec7et** [Elysian-Realme/FuGfConfig#3]
我使用Qx代理软件，添加了Apple的分流，平时使用地图、App Store这些可以看到有相关的网络请求，在流量监控和流速监控里可以看到相关内容。
但是平时在使用Facetime的时候，或者是微信视频通话、微信语音通话，都看不到相关的网络请求，也没有实时速率。
因为本仓库的readme里有提到说 ```AppleRules 是与本地化息息相关的规则，比如地图、天气、查找、Facetime、Apple Pay ( iCloud 上传与下载也归于此规则集``` ，不知道大佬对这个情况是否有所了解？
😂实在是太让我费解了，有机会还请指教指教。谢谢。

**Comment by dunlanl** [comment]
我略有了解，我建议你先看一下 dns 的问题，以及把 AppleRules 设置为直连试试

**Comment by sec7et** [comment]
> 我略有了解，我建议你先看一下 dns 的问题，以及把 AppleRules 设置为直连试试

刚我试了下
[general] 里的配置：
excluded_routes=239.255.255.250/32
udp_whitelist 被注释

dns 使用 119.29.29.29，未开启 qx 的 dns劫持 功能。
AppleRules 强制使用 direct 。
使用流量跟我连接了 Wifi 的苹果设备打 facetime ，qx 的流量监控和流速监控仍然看不到任何数据。
也就是说 facetime 有画面有声音，但是 qx 里应该就是没有任何关于这方面的请求信息。
😂是否哪里的设置需要改动的呢？

**Comment by dunlanl** [comment]
不好意思，看不到请求这个我不太清楚，我一开始以为是连不上FaceTime，那个dns的建议是关于连不上FaceTime的

**Comment by sec7et** [comment]
> 不好意思，看不到请求这个我不太清楚，我一开始以为是连不上FaceTime，那个dns的建议是关于连不上FaceTime的

哈哈哈好的好的。或者您这边方不方便试下自己给其他设备打个 facetime 的？我猜您应该是用 Loon 的？😂想说有没有可能是代理App的关系。
