### ISSUE TITLE
AppleUpdateRules可以增加一些规则

### ISSUE THREAD

**Issue by Mosaic-c** [Elysian-Realme/FuGfConfig#7]
DOMAIN-SUFFIX,ocsp2.apple.com
DOMAIN-SUFFIX,swscan.apple.com

**Comment by TruElysian** [comment]
好的，感谢反馈

**Comment by TruElysian** [comment]
`ocsp2.apple.com` 是检测 app 签名验证的 URL 吧？

**Comment by TruElysian** [comment]
`swscan.apple.com` 已收录

`ocsp2.apple.com` 是证书验证相关
